---
version: "3"

tasks:
  snyk-login:
    deps:
      - :common:npm-snyk
    env:
      SNYK_API_TOKEN:
        sh: snyk config get api
    cmds:
      - |
        if [ -z "$SNYK_API_TOKEN" ]; then
          bash .common/log warn "You are not currently authenticated with Snyk. Sign in by running \`snyk auth\`."
          bash .common/log info "Initiating the sign-in process for Snyk by running \`snyk auth\`.."
          snyk auth
        fi
